source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'AFSReusableDisplayKit_Example' do
  
  use_frameworks!
  pod 'AFSReusableDisplayKit', :path => '../'
  
  target 'AFSReusableDisplayKit_Tests' do
    
    inherit! :search_paths
    
  end
  
end
